# Generated by Django 3.0.6 on 2020-05-29 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reg_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register_data',
            name='mobile',
            field=models.BigIntegerField(),
        ),
    ]
